---
apiVersion: v2
appVersion: v3.0.8.1507
description: Smart PVR for newsgroup and bittorrent users
name: sonarr
version: 0.1.0
kubeVersion: ">=1.22.0-0"
keywords:
  - sonarr
  - torrent
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/sonarr
icon: https://github.com/Sonarr/Sonarr/blob/phantom-develop/Logo/512.png?raw=true
sources:
  - https://github.com/Sonarr/Sonarr
  - https://github.com/k8s-at-home/container-images
maintainers:
  - name: CoolMintChocolate
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.3.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Init chart
