---
apiVersion: v2
appVersion: v1.0.3
description: Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements
name: bazarr
version: 0.1.0
kubeVersion: ">=1.22.0-0"
keywords:
  - bazarr
  - radarr
  - sonarr
  - subtitles
  - usenet
  - torrent
home: https://github.com/CoolMintChocolate/charts/tree/master/charts/bazarr
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png
sources:
  - https://github.com/morpheus65535/bazarr
maintainers:
  - name: CoolMintChocolate
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.3.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Init chart
