---
apiVersion: v2
appVersion: v2.0.3-2201906121747
description: Deluge is a torrent download client
name: deluge
version: 0.1.2
kubeVersion: ">=1.22.0-0"
keywords:
  - deluge
  - torrent
home: https://github.com/CoolMintChocolate/charts/tree/master/charts/deluge
icon: https://avatars2.githubusercontent.com/u/6733935?v=3&s=200
sources:
  - https://hub.docker.com/r/linuxserver/deluge/
  - https://deluge-torrent.org/
maintainers:
  - name: CoolMintChocolate
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.3.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Align kubeversion with common chart
