---
apiVersion: v2
appVersion: v1.28.0.5999-97678ded3
description: Plex Media Server
name: plex
version: 0.1.0
kubeVersion: ">=1.22.0-0"
keywords:
  - plex
  - plex-media-server
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/plex
icon: https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png
sources:
  - https://github.com/k8s-at-home/charts/tree/master/charts/stable/plex
  - https://github.com/k8s-at-home/container-images/
maintainers:
  - name: CoolMintChocolate
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.3.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Init chart
